version: "3.6"
services:
  postgresdb:
    image: postgres:13.1
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: "SEjNMf4795LHAhus3E"
    expose:
      - 5432
    networks: 
      - local-bridge
  

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks: 
      - local-bridge

  seapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seapi
    depends_on:
      - postgresdb
    volumes:
      - ./seapi:/app
    ports:
      - "5000:80"
      - "5001:443"
    networks: 
      - local-bridge
    
networks:
  local-bridge:
    driver: bridge
