version: "3.6"
services:
  se-netapi:
    build:
      context: ./SEProject
      dockerfile: api-dockerfile
    container_name: se-netapi
    volumes:
      - ./senetapi:/app
    ports:
      - 5000:80

  se-angularapp:
    build:
      context: ./ClientApp
      dockerfile: app-dockerfile
    container_name: se-angularapp
    ports:
      - 4200:80
