version: "3.6"
services:
  postgresdb:
    image: postgres:13.1
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: "SEjNMf4795LHAhus3E"
    ports:
      - 5432:5432

  seapi:
    build:
      context: ./SEProject
      dockerfile: api-dockerfile
    container_name: seapi
    depends_on:
      - postgresdb
    volumes:
      - ./seapi:/app
    ports:
      - 5000:80

  seangularapp:
    build:
      context: ./SE.Web
      dockerfile: app-dockerfile
    container_name: seangularapp
    ports:
      - 4200:80
    depends_on:
      - seapi